### ISSUE TITLE
Information about the Data

### ISSUE THREAD

**Issue by dsleo** [google/uis-rnn#1]
Hello,

Thank you for open sourcing this ! I haven't found information regarding the data you provide. What is it/ where does it come from ?

**Comment by wq2012** [comment]
The files under `data/` are toy data that are manually generated. Its only purpose is to show how to use the API.

The docstrings of `fit()` and `predict()` will give you a better idea.

**Comment by MuruganR96** [comment]
@wq2012  sir how can i form that kind of structure data like train.npz.

```
from scipy.io.wavfile import read
a = read("adios.wav")
numpy.array(a[1],dtype=float)
np.savez_compressed('train.npz', array1=a[1])
b = np.load('train.npz')
```

this is k or not for test the demo.py utterences ?
help me sir?

**Comment by wq2012** [comment]
`tests/integration_test.py` is the best example for you to understand the APIs.
