### ISSUE TITLE
handle overlapped speech

### ISSUE THREAD

**Issue by PES2g** [google/uis-rnn#18]
In your paper, during evaluation, you exclude overlapped speech. Which one below is the solution? 
1. You method process the whole audio, ignore the error during the overlapped speech
2. You method first trim the overlapped part from the audio, then process the trimmed audio

And during training, which is the solution ?

**Comment by wq2012** [comment]
Our method is consistent for both training and testing:

1. Process the entire audio to produce speaker embeddings. (we don't want to run speaker embedding LSTM on manually trimmed/concatenated audios)
2. Remove the speaker embeddings that correspond to overlapped speakers, in both training and testing data.
3. For computing diarization errors, note that the overlapping speech has been removed from **both the numerator and the denominator**.

**Comment by chienducnguyen** [comment]
How you know what speaker embeddings that correspond to overlapped speakers to remove?
