### ISSUE TITLE
Obscurity involved in sampling rate information of datasets used

### ISSUE THREAD

**Issue by HarshaVardhanMA** [google/uis-rnn#23]
It is specified in the paper that, Voxceleb (which has a sampling rate of 16k) is one among the public datasets used for training the d-vector model, while the testing dataset is 2000 CALLHOME (which is 8k).
Please clarify this sampling rate mismatch issue.

**Comment by wq2012** [comment]
Our acoustic features, log-mel filterbank energies, are agnostic of the sampling rate.

Also, you can always downsample/upsample the signals.
