### ISSUE TITLE
 about the version of pytorch and tensorflow

### ISSUE THREAD

**Issue by Aurora11111** [google/uis-rnn#36]
TensorFlow implementation by Janghyun1230
PyTorch implementaion by HarryVolek - with UIS-RNN integration
hello,Are the two versions above have the same algorithm with uis-rnn ?
what's the different between them ?
Can all of them  identify enrollment utterances and unenrollment utterances?
Can all  of them identify new speakers which is untrained ?

**Comment by wq2012** [comment]
These two libraries are for speaker embedding learning, not for diarization. They solve completely different problems. Please read the corresponding papers first.

For more details about these two repos, please contact their authors directly.
