### ISSUE TITLE
[Question]Performance degrade for different win size

### ISSUE THREAD

**Issue by FengLeee** [google/uis-rnn#38]
## Describe the question
i train embedding lstm with variable length batch size, about [24，160]，then i get d-vector with win size 160frame in this model, and use the d-vector train uis-rnn,  the uis-rnn predict result is good(90%)。but when i use  win size 40frame get the d-vector and train uis-rnn  the uis-rnn predict result is bad (40%)。what the reason cause this problem？

**Comment by wq2012** [comment]
Please clarify your setup:

- [24, 160]: What's the unit here? Frame or ms? If frame, what's your frame size and step?
- 40frame: Again, what's your frame size and step?
- win: Does your window overlap? If yes, how much?
- Which training and testing dataset are you using for uis-rnn? Which dataset are you using for d-vector training?
