### ISSUE TITLE
[Question] Can I use speaker annotated datasets in other language rather than English?

### ISSUE THREAD

**Issue by muntasir2000** [google/uis-rnn#44]
## Describe the question
Hi,
This might be a naive question. But can I use speaker annotated speech corpora from different languages (English, Mandarin etc), combine them and train the speaker embedding component? Are speaker embeddings/UIS-RNN language independent?

## My background

Have I read the `README.md` file?
yes

Have I searched for similar questions from closed issues?
yes

Have I tried to find the answers in the paper *Fully Supervised Speaker Diarization*?
yes

Have I tried to find the answers in the reference *Speaker Diarization with LSTM*?
yes

Have I tried to find the answers in the reference *Generalized End-to-End Loss for Speaker Verification*?
yes

**Comment by wq2012** [comment]
@muntasir2000 Yes! And we are already doing that ourselves.

In the paper "Generalized End-to-End Loss for Speaker Verification", we described a technique called **MultiReader**. We had been using MultiReader to train a single more for multiple languages (currently 8 langauges).

In the paper "Fully Supervised Speaker Diarization", in Section 4.1, we also mentioned that our d-vector V2 and V3 models are trained with non-English data, using MultiReader.
