### ISSUE TITLE
Predict function unstable for different input

### ISSUE THREAD

**Issue by Nanda-Nandan** [google/uis-rnn#45]
Hi Sir,
I have trained UIS-RNN model on timit dataset(academy approximately 600 speakers).For prediction I have choosen 3 speakers from the above mentioned dataset. For d-vector creation as input to UIS-RNN I have used GE2E loss based embedding and concatenating the embedding for 3 speakers.It is giving me correct prediction.Note that here all 3 speaker have 8 or 9 utterances(.wav file) and i am concatenating embedding of each.But If I am taking a long audio and(4-6 minutes .wav and 4 speakers) and doing the embedding for the full audio using same process while predicting i am getting wrong result.

Kindly help me to resolve the issue.
If you need the files like model and d vector please let me know i will upload it.

below are the prediction result for both:-
Correct Prediction(timit data set 3 speaker concatenation ):-
Predicted labels:
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]

wrong prediction(longer audio 4-6 minutes .wav):-

Predicted labels:
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

**Comment by wq2012** [comment]
Could you take a look at the conversation under #43 ? Seems you are not training UIS-RNN on real dialogues.

UIS-RNN is a supervised learning technique that tries to learn these information from training data:

- Dialogue styles.
- Speaker turn frequency.
- Domain-specific hints for speaker turns.

If you are purely concatenating independent utterances, UIS-RNN isn't expected to perform well.

**Comment by Nanda-Nandan** [comment]
Thanks Sir,

You are right.my training data is artificial one,by concatenating individual speaker segments.
I got your points regarding the query but here are some things I am not clear actually.

1. When you are saying domain specific hints does it mean that the real audio data we will give for training should be correspond to specific domain
2. Is there any  real time data available for diarization training(I can buy).
3. Why the trained model is working fine on predicting on test data where i have concatenated 3 speakers, my pov is if the model is not properly trained it should work bad for any type of data.

**Comment by wq2012** [comment]
> When you are saying domain specific hints does it mean that the real audio data we will give for training should be correspond to specific domain

I mostly mean, your training data should be consistent with what you want to test on. E.g. you plan to diarize phone calls for Company A's customer phone records, then train the UIS-RNN on exactly Company A's customer phone records, instead of YouTube videos - that's what supervised learning is all about.

> Is there any real time data available for diarization training(I can buy).

Yes! Check this out: https://github.com/wq2012/awesome-diarization (and feel free to contribute!)

Some datasets are ridiculously expensive. Definitely check whether your organization has already purchased them first, and if not also try to experiment with free datasets (e.g. we found ICSI very helpful).

> Why the trained model is working fine on predicting on test data where i have concatenated 3 speakers, my pov is if the model is not properly trained it should work bad for any type of data.

That I don't know. I'm not familiar with your experiment setup so don't want to conclude anything without evidence.

**Comment by Nanda-Nandan** [comment]
o

> I mostly mean, your training data should be consistent with what you want to test on. E.g. you plan to diarize phone calls for Company A's customer phone records, then train the UIS-RNN on exactly Company A's customer phone records, instead of YouTube videos - that's what supervised learning is all about.

Is google cloud speech to text uses uisrnn? if yes, how its giving good result on different domain data(call center data, conference call data).Did it mean it has been trained on various domains

**Comment by wq2012** [comment]
> Is google cloud speech to text uses uisrnn? if yes, how its giving good result on different domain data(call center data, conference call data).Did it mean it has been trained on various domains

Unfortunately, that's not something I'm supposed to disclose here. We cannot talk about any specific products by Google on GitHub.
