### ISSUE TITLE
How to convert audio data into test data of algorithm for testing

### ISSUE THREAD

**Issue by zyc1310517843** [google/uis-rnn#46]
## Describe the question
A clear and concise description of what the question is.

## My background

Have I read the `README.md` file?
* yes

Have I searched for similar questions from closed issues?
* yes

Have I tried to find the answers in the paper *Fully Supervised Speaker Diarization*?
* yes

Hello, I have read README.md I want to convert my audio data into the test and training data needed by the model. How can I do this? I have also tried the third-party methods provided in  README.md. However, they are for specific data sets, such as TIMIT, using our own audio data can not run successfully. Thank you very much for your guidance.

**Comment by wq2012** [comment]
You can use any **continuous speaker embedding** technique to do that.

I listed a few here: https://github.com/wq2012/awesome-diarization#speaker-embedding

Not all of them supports **continuous** embeddings. You need to do some research on your own here.
