### ISSUE TITLE
Any plan on upgrading to pytorch 1.0+?

### ISSUE THREAD

**Issue by tanvirfuad** [google/uis-rnn#47]
## Describe the question
Wanted to use in Tesla 4 on Google Cloud VM. Apparently, they do not support lower versions of CUDA other than CUDA 10 on T4. And, for pytorch 0.4.1, it requires a lower version of CUDA.

## My background
I just finished my masters and working as a speech recognition engineer.

Have I read the `README.md` file?
* yes

Have I searched for similar questions from closed issues?
* yes

Have I tried to find the answers in the paper *Fully Supervised Speaker Diarization*?
* yes

Have I tried to find the answers in the reference *Speaker Diarization with LSTM*?
* yes

Have I tried to find the answers in the reference *Generalized End-to-End Loss for Speaker Verification*?
* yes

**Comment by wq2012** [comment]
@tanvirfuad Thanks for the suggestion. It's a good point. I will take a look at that later.

Also, did you try to run uis-rnn (as it is) with PyTorch 1.0? And if yes, did you see any breakage?

I doubt it may just work correctly with PyTorch 1.0 without any changes.

**Comment by tanvirfuad** [comment]
Thank you for the quick reply. And yes, It does work on pytorch 1.0. Thank you so much for pointing the direction. Earlier, it was breaking for pytorch 1.1, but I did not try on 1.0. I actually forgot what error I was getting. If you want I can try that again and post here. Otherwise, please feel free to close the issue :)

**Comment by wq2012** [comment]
No worries. I can give it a try with PyTorch 1.1 myself.
