### ISSUE TITLE
The number of speakers and whether the content of the speaker needs to be the same。

### ISSUE THREAD

**Issue by zyc1310517843** [google/uis-rnn#49]
## Describe the question
A clear and concise description of what the question is.

## My background

Have I read the `README.md` file?
* yes/no - if you answered no, please stop filing the issue, and read it first

Have I searched for similar questions from closed issues?
* yes/no - if you answered no, please do it first

Have I tried to find the answers in the paper *Fully Supervised Speaker Diarization*?
* yes/no

Have I tried to find the answers in the reference *Speaker Diarization with LSTM*?
* yes/no

Have I tried to find the answers in the reference *Generalized End-to-End Loss for Speaker Verification*?
* yes/no
Hello, preparations have been completed. Now we want to train our voice data. I want to ask three questions: 1. How many speakers do we need at least? 2. How long does each speaker need to say a few words? 3. Does each speaker need to speak the same sentence? Thank you for your guidance.

**Comment by wq2012** [comment]
Please find the answers in the above mentioned papers.
