### ISSUE TITLE
[Question] how to relate sigma2_prior_loss() with the paper

### ISSUE THREAD

**Issue by jprobichaud** [google/uis-rnn#52]
First, thanks for sharing this implementation.

We're trying to understand the core of the training methods with the paper' equations.  We're able to make sense of most of it, but the `sigma2_prior_loss()` in `loss_func.py` escape our understanding.

Could someone provide some explanation for it?  How to derive that loss from the paper?

Thanks in advance!

**Comment by wq2012** [comment]
Please see issue #10 for the answers.

Regularization loss terms were not discussed in paper since it had a 4-page limit.
