### ISSUE TITLE
Is UIS-RNN the technique used in Speaker Diarization in Google Speech-to-text API? [Question]

### ISSUE THREAD

**Issue by blazejdolicki** [google/uis-rnn#54]
## Describe the question
Is UIS-RNN the technique used in Speaker Diarization in Google Speech-to-text API?

## My background

Have I read the `README.md` file?
* yes

Have I searched for similar questions from closed issues?
* yes

Have I tried to find the answers in the paper *Fully Supervised Speaker Diarization*?
* yes

Have I tried to find the answers in the reference *Speaker Diarization with LSTM*?
* yes

Have I tried to find the answers in the reference *Generalized End-to-End Loss for Speaker Verification*?
* yes

**Comment by wq2012** [comment]
We are **NOT** supposed to reveal any details about specific Google products on GitHub.

Please only use GitHub Issues for discussions related to the paper or the library.

For questions related to any Google products, please contact the customer service directly.
