### ISSUE TITLE
[Question] How can I get the text of each speaker after speaker diarization?

### ISSUE THREAD

**Issue by rowhitswami** [google/uis-rnn#59]
## Describe the question
A clear and concise description of what the question is.
I want to perform some sentiment analysis work after speaker diarization. This project looks very promising for my task. It would be really great if you can help me out.
## My background
I'm a 4th-year engineering student from India, currently working as a Software Engineering Intern as InterviewBit

Have I read the `README.md` file?
* yes

Have I searched for similar questions from closed issues?
* yes

Have I tried to find the answers in the paper *Fully Supervised Speaker Diarization*?
* yes

Have I tried to find the answers in the reference *Speaker Diarization with LSTM*?
* yes

Have I tried to find the answers in the reference *Generalized End-to-End Loss for Speaker Verification*?
* yes

**Comment by wq2012** [comment]
You need ASR. Unfortunately we don't work on that.

**Comment by rowhitswami** [comment]
Any reference would be a great help.
Thank you @wq2012

**Comment by wq2012** [comment]
Just Google search ASR, or automatic speech recognition.
