### ISSUE TITLE
Repo

### ISSUE THREAD

**Issue by chrisspen** [google/uis-rnn#66]
Again, this is a  followup to [this](https://github.com/google/uis-rnn/issues/65).

You said I could re-open the issue after you've closed it if I have any other questions. Unfortunately, this is not the case. You've configured your repo so that only you have the permission to re-open issues.

Thank you for the clarification. I mistakenly thought uis-rnn was speech recognition algorithm, but now I see it's a clustering algorithm.

**Comment by wq2012** [comment]
OK. The configuration seems to be a global config for all Google repos. I thought anyone could reopen issues.

Glad you figured it out.
