### ISSUE TITLE
I run the demo use toy data, found loss is negative number.

### ISSUE THREAD

**Issue by Naminwang** [google/uis-rnn#69]
## Describe the question
I run the demo use toy data, found loss is negative number. Is that something wrong, or it is normal.

## My background

Have I read the `README.md` file?
* yes

Have I searched for similar questions from closed issues?
* yes

Have I tried to find the answers in the paper *Fully Supervised Speaker Diarization*?
* yes

Have I tried to find the answers in the reference *Speaker Diarization with LSTM*?
* yes

Have I tried to find the answers in the reference *Generalized End-to-End Loss for Speaker Verification*?
* yes

**Comment by wq2012** [comment]
Yes, loss is negative.
