### ISSUE TITLE
how to control the number of different speaker when predicting?

### ISSUE THREAD

**Issue by NewEricWang** [google/uis-rnn#78]
## Describe the question
In my experiment, I find the speaker number predicted by uis-rnn model is more than real number. 
I want to know how to control the different  speaker number predicted by uis-rnn model. 
Which parameters in inference stage can do it? 

## My background

Have I read the `README.md` file?
* yes/no - if you answered no, please stop filing the issue, and read it first

Have I searched for similar questions from closed issues?
* yes/no - if you answered no, please do it first

Have I tried to find the answers in the paper *Fully Supervised Speaker Diarization*?
* yes/no

Have I tried to find the answers in the reference *Speaker Diarization with LSTM*?
* yes/no

Have I tried to find the answers in the reference *Generalized End-to-End Loss for Speaker Verification*?
* yes/no

**Comment by wq2012** [comment]
It's not supported, see Issue #26 

However, you can try to lower `--crp_alpha`.
