### ISSUE TITLE
Change input size

### ISSUE THREAD

**Issue by surasakBoonkla** [google/uis-rnn#81]
Hello,

I am trying your code for dizrizaition by using another type of vector.
The problem is I need to change the input size.
In your training example, your vector length is 256.
If I have input vector length 512, what shall I do?
Please, suggest me.

Regards,

Surasak
National Electronics and Computer Technology Center.

**Comment by wq2012** [comment]
All arguments are defined here: https://github.com/google/uis-rnn/blob/master/uisrnn/arguments.py
