### ISSUE TITLE
Is is possible to pre-load the model for multiple request?

### ISSUE THREAD

**Issue by luys8611** [google/uis-rnn#83]
For single file, it works fine.
Now I'm trying to process lots of files, for example 10000 audio files.
I made a script for loop processing, but it is loading diarization model in each calling.
I tried to change it to pre-load model, but not worked.
```
ValueError: Tensor Tensor("lambda_1/l2_normalize:0", shape=(?, 512), dtype=float32) is not an element of this graph.
```
Is there a way for it? Thanks for anyone, any help.

**Comment by wq2012** [comment]
See https://github.com/google/uis-rnn/issues/32

We added `uisrnn.parallel_predict()`.
