### ISSUE TITLE
[Question] The dimension of toy test data [test_sequence] is (25, 95, 256) what does the first 2 dimension represent? Toy train data [train_sequence] has dimension (4627, 256) which is understandable.

### ISSUE THREAD

**Issue by saumyaborwankar** [google/uis-rnn#85]
## Describe the question
Help regarding understanding the toy data provided

**Comment by wq2012** [comment]
Please check the README.md file and the documentation:
https://google.github.io/uis-rnn/uisrnn.html#uisrnn.uisrnn.UISRNN.predict
