### ISSUE TITLE
rnn initial state trainable 

### ISSUE THREAD

**Issue by ZimingY** [google/uis-rnn#87]
Hi I noticed that the rnn init_hidden is set as nn.Parameters and make it trainable 
https://github.com/google/uis-rnn/blob/51bca2f383f75397abe913a39f437f62d2852bcf/uisrnn/uisrnn.py#L94
In the paper, however, it said "where we can assume x0 = 0 and h0 = 0, meaning all GRU instances are initialized with the same zero state".  So shouldn't it be same for all training instances? 
And will nn.Parameters result to overfitting to training data? 

Thanks!

**Comment by wq2012** [comment]
Thanks for the question. IIRC, whether the initial states are trainable makes very small difference to the results. So it doesn't really matter.
